# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160806_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='edad',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
