# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160806_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cedula',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
