# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160808_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(choices=[(None, ''), ('F', 'Mujer'), ('M', 'Hombre')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='rol',
            field=models.CharField(choices=[(None, ''), ('C', 'Cliente'), ('A', 'Administrador'), ('S', 'Superusuario')], default=None, max_length=1),
        ),
    ]
